# Generated by Django 5.1.1 on 2024-11-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cc', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
    ]
