# Generated by Django 5.1.2 on 2024-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_payments',
            field=models.IntegerField(default=1),
        ),
    ]
