# Generated by Django 5.1.2 on 2024-11-07 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_credit_total_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
