# Generated by Django 5.1.2 on 2024-11-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='due_to',
        ),
    ]
