# Generated by Django 5.1.2 on 2024-11-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_rename_date_payment_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_to',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
