# Generated by Django 5.1.1 on 2024-09-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credit_id', models.IntegerField()),
                ('Status', models.CharField(choices=[('started', 'Started'), ('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended')], max_length=10)),
                ('Created_at', models.DateField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
