# Generated by Django 5.1.1 on 2024-09-28 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_payment_credit_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('cc', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Delayed_value',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='value',
        ),
        migrations.AlterField(
            model_name='credit',
            name='Created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_STATUS',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='credit',
            name='Client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Delayed_Value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='Value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
