# Generated by Django 5.1.1 on 2024-09-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_credit_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='Credit_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Payment_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Client_id',
        ),
    ]
